#!/usr/bin/env python3
"""Convert animation frames into a QMK OLED sprite header.

    ./tools/frames2qmk.py art.txt            > keymaps/default/sprite.h
    ./tools/frames2qmk.py f1.png f2.png ...  > keymaps/default/sprite.h
    ./tools/frames2qmk.py walk.gif           > keymaps/default/sprite.h

ASCII input needs no dependencies: '#', '1', 'X' or '*' = lit, anything else
dark, frames separated by one or more blank lines. Image input needs Pillow
(`pipx install pillow` or `pip3 install --user pillow`).

WHY THIS EXISTS: web converters such as image2cpp emit HORIZONTAL bit packing,
where each byte is 8 pixels across a row. QMK's OLED buffer is the opposite --
page-major with each byte holding 8 VERTICAL pixels (bit 0 = top of the page).
Feeding image2cpp output straight to oled_write_raw() renders shredded garbage.
This script packs it the way QMK actually wants.
"""
import sys

def die(msg):
    sys.stderr.write("error: %s\n" % msg)
    raise SystemExit(1)

def load_ascii(path):
    blocks, cur = [], []
    for line in open(path):
        line = line.rstrip("\n")
        if line.strip() == "":
            if cur: blocks.append(cur); cur = []
        else:
            cur.append(line)
    if cur: blocks.append(cur)
    frames = []
    for b in blocks:
        w = max(len(r) for r in b)
        frames.append([[1 if ch in "#1Xx*" else 0 for ch in r.ljust(w)] for r in b])
    return frames

def load_images(paths):
    try:
        from PIL import Image, ImageSequence
    except ImportError:
        die("image input needs Pillow. Install it, or use ASCII-art input instead.")
    frames = []
    for p in paths:
        im = Image.open(p)
        seq = ImageSequence.Iterator(im) if getattr(im, "is_animated", False) else [im]
        for f in seq:
            g = f.convert("L")
            frames.append([[1 if g.getpixel((x, y)) >= 128 else 0
                            for x in range(g.width)] for y in range(g.height)])
    return frames

def pack(grid):
    """Page-major, 8 vertical pixels per byte, bit 0 = topmost row of the page."""
    h, w = len(grid), len(grid[0])
    if h % 8:
        die("frame height %d is not a multiple of 8 (a page is 8 pixels tall)" % h)
    out = []
    for page in range(h // 8):
        for x in range(w):
            byte = 0
            for bit in range(8):
                if grid[page * 8 + bit][x]:
                    byte |= 1 << bit
            out.append(byte)
    return out

def main(argv):
    if not argv:
        die("usage: frames2qmk.py <art.txt | image...>")
    frames = load_ascii(argv[0]) if argv[0].lower().endswith((".txt", ".art")) \
             else load_images(argv)
    if not frames:
        die("no frames found")

    h, w = len(frames[0]), len(frames[0][0])
    for i, f in enumerate(frames):
        if (len(f), len(f[0])) != (h, w):
            die("frame %d is %dx%d but frame 0 is %dx%d -- all frames must match"
                % (i, len(f[0]), len(f), w, h))
    if w > 128:
        die("frame width %d exceeds the 128px panel" % w)

    print("// Generated by tools/frames2qmk.py -- do not edit by hand.")
    print("// %d frame(s), %dx%d, QMK page format, %d bytes/frame"
          % (len(frames), w, h, w * h // 8))
    print("#define SPRITE_W      %d" % w)
    print("#define SPRITE_PAGES  %d" % (h // 8))
    print("#define SPRITE_FRAMES %d" % len(frames))
    print("static const uint8_t PROGMEM sprite[SPRITE_FRAMES][SPRITE_PAGES * SPRITE_W] = {")
    for f in frames:
        d = pack(f)
        print("    {")
        for i in range(0, len(d), 16):
            print("        " + ", ".join("0x%02X" % b for b in d[i:i+16]) + ",")
        print("    },")
    print("};")
    sys.stderr.write("ok: %d frame(s) %dx%d, %d bytes total\n"
                     % (len(frames), w, h, len(frames) * w * h // 8))

if __name__ == "__main__":
    main(sys.argv[1:])
